# Generated by Django 2.2.6 on 2019-11-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feed_image'),
    ]

    operations = [
    ]
