# Generated by Django 2.2.6 on 2019-11-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191110_1716'),
    ]

    operations = [
    ]
