# Generated by Django 2.2.6 on 2019-11-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191110_2129'),
    ]

    operations = [
    ]
