# Generated by Django 2.2.6 on 2019-11-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191111_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(default='default_image.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='takes',
            name='id',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Profile'),
        ),
    ]
