# Generated by Django 2.2.6 on 2019-11-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191111_2140'),
    ]

    operations = [
    ]
