# Generated by Django 2.2.6 on 2019-11-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191111_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='star',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
