# Generated by Django 2.2.6 on 2019-11-12 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_takes_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 12, 4, 19, 59, 434189)),
        ),
    ]
