# Generated by Django 2.2.6 on 2019-11-12 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191112_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
