# Generated by Django 2.2.6 on 2019-11-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191112_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemble',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category'),
        ),
    ]
