# Generated by Django 2.2.6 on 2019-11-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_assemble_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemble',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
