# Generated by Django 2.2.6 on 2019-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191118_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemble',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
