# Generated by Django 2.2.6 on 2019-11-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191118_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemble',
            name='photo',
            field=models.ImageField(default='default_image.jpeg', upload_to=''),
        ),
    ]
