# Generated by Django 2.2.6 on 2019-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191119_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
