# Generated by Django 2.2.6 on 2019-12-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_likefeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likefeed',
            name='like',
        ),
    ]
