# Generated by Django 2.2.6 on 2019-12-03 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_likefeed_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAssemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assemble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Assemble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profile')),
            ],
            options={
                'db_table': 'likeassemble',
                'unique_together': {('id', 'assemble')},
            },
        ),
    ]
